### PR TITLE
Added AuthenticationCleartextPassword flow

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
Hi,

I needed the AuthenticationCleartextPassword flow, which wasn't implemented. Would you consider merging it?

Thanks.

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
@goodlyrottenapple The author is now taking medical care. It would take time to preview this PR. Sorry for your inconvenience.

**Comment by goodlyrottenapple** [comment]
No worries. There is no rush from my side.

**Comment by kakkun61** [comment]
@goodlyrottenapple Thanks for your PR! It looks good, but I'm sorry that the master branch is force-pushed. Please cherry-pick https://github.com/iij-ii/postgresql-pure/pull/1/commits/a804ae57d78e86e535e9a11a6b993bdf2a965b51 to the current master branch.

**Comment by goodlyrottenapple** [comment]
Done

**Comment by goodlyrottenapple** [comment]
Thanks :)

**Pull request merged**
